name: Publish to npm

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: NPM Registry token
        required: true

jobs:
  publish_packages:
    name: Publish packages to npm and GPR
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@sophos-factory'
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
      - run: npm run build:runtime

      - name: Publish to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to GPR
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sophos-factory'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
