name: test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node ${{ matrix.version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - run: node -e "console.log('FACTORY_CLI_PATH'+'='+path.resolve('./bin/refactrctl.js'))" >> $GITHUB_ENV
        shell: bash

      - run: npm ci
      - run: npm run lint
      - run: npm run build:runtime

      - run: npm run test:unit
      - run: npm run test:e2e -- -u
        env:
          FACTORY_ADDRESS: ${{ secrets.FACTORY_ADDRESS }}
          FACTORY_STATIC_AUTH_TOKEN: ${{ secrets.FACTORY_AUTH_TOKEN }}
          FACTORY_DYNAMIC_AUTH_TOKEN: ${{ secrets.FACTORY_AUTH_TOKEN2 }}
