name: Run tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    uses: ./.github/workflows/all-tests.yml
    with:
      FACTORY_ADDRESS: 'https://api.dev.factory.sophos.com/v1'
    secrets:
      FACTORY_AUTH_TOKEN: ${{ secrets.FACTORY_AUTH_TOKEN }}
      FACTORY_AUTH_TOKEN2: ${{ secrets.FACTORY_AUTH_TOKEN2 }}
